MERGE
INTO
    cwsuser.x_property x
USING (
    SELECT (SELECT CASE WHEN NVL(MAX(x_property_id), 1) > 1 THEN MAX(x_property_id) ELSE 0 END FROM cwsuser.x_property) + ROW_NUMBER() OVER (ORDER BY seq) x_property_id, name, storeent_id, language_id, value, description FROM
    (      


    
    SELECT 1 seq, 'MIN_PRICE' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Min Price' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 2 seq, 'MIN_PRICE' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, 'Prix min' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 3 seq, 'MAX_PRICE' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Max Price' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 4 seq, 'MAX_PRICE' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, 'Prix max' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 5 seq, 'LIST_PRICE_MULTIPLIER' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'List Price multiplier' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 6 seq, 'LIST_PRICE_MULTIPLIER' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, 'Multiplicateur de prix courant' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 7 seq, 'LIST_PRICE_MATRIX' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'List Price Matrix' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 8 seq, 'LIST_PRICE_MATRIX' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, 'Matrice des prix courants' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 9 seq, 'AAPERR_PRICE_MATRIX_RANGE_OVERLAP' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Please do not enter a value which already exists in the price range.' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 10 seq, 'AAPERR_PRICE_MATRIX_RANGE_OVERLAP' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, REPLACE(REPLACE('Veuillez ne pas ajouter une valeur qui existe d_j@ dans la fourchette de prix','_', u&'\00e9'),'@',u&'\00e0') VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 11 seq, 'PRICE_MATRIX_UNDO_DELETE' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'The row has been deleted' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 12 seq, 'PRICE_MATRIX_UNDO_DELETE' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, REPLACE('Cette ligne a _t_ effac_e','_',u&'\00e9') VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 13 seq, 'PRICE_MATRIX_UNDO' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Undo' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 14 seq, 'PRICE_MATRIX_UNDO' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, 'Annuler' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 15 seq, 'PRICE_MATRiX_DESC' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'List Price Matrix gives you the ability to modify the list price that displays on the website. Set your own thresholds and markup based on your unit price/cost' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 16 seq, 'PRICE_MATRiX_DESC' NAME, 0 STOREENT_ID, -2 LANGUAGE_ID, REPLACE(REPLACE('La Matrice des prix courants permet de modifier les prix courants affich_s sur le site Web. R_glez vos seuils et marges brutes selon votre co@t unitaire','_',u&'\00e9'),'@', u&'\00fb') VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    
)) AS T
ON (X.NAME = T.NAME AND X.LANGUAGE_ID = T.LANGUAGE_ID)
WHEN MATCHED THEN
  UPDATE SET
    VALUE = T.VALUE,
    LASTUPDATE = CURRENT TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (X_PROPERTY_ID, NAME, LANGUAGE_ID, STOREENT_ID, VALUE, LASTUPDATE)
  VALUES (T.X_PROPERTY_ID, T.NAME, T.LANGUAGE_ID, T.STOREENT_ID, T.VALUE, CURRENT TIMESTAMP);





MERGE
INTO
    cwsuser.x_property x
USING (
    SELECT (SELECT CASE WHEN NVL(MAX(x_property_id), 1) > 1 THEN MAX(x_property_id) ELSE 0 END FROM cwsuser.x_property) + ROW_NUMBER() OVER (ORDER BY seq) x_property_id, name, storeent_id, language_id, value, description FROM
    (      


    
    SELECT 1 seq, 'AAPERR_PRICE_MATRIX_MISSING_PARAMS' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Missing required Parameters' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 2 seq, 'AAPERR_PRICE_MATRIX_MAX_RECORDS_LIMIT' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'only 8 records are allowed per account.' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 3 seq, 'AAPERR_PRICE_MATRIX_INVALID_LOW_RANGE_VALUE' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Invalid low range value' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 4 seq, 'AAPERR_PRICE_MATRIX_INVALID_HIGH_RANGE_VALUE' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Invalid high rangeValue' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 5 seq, 'AAPERR_PRICE_MATRIX_INVALID_MARKUP_VALUE' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Invalid mark up value' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 6 seq, 'AAPERR_PRICE_MATRIX_CREATE_FAILED' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Create Operation failed.' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 7 seq, 'AAPERR_PRICE_MATRIX_READ_FAILED' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Read Operation failed' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 8 seq, 'AAPERR_PRICE_MATRIX_UPDATE_FAILED ' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Update Operation failed' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
	UNION ALL SELECT 9 seq, 'AAPERR_PRICE_MATRIX_DELETE_FAILED ' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Delete Operation failed' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    UNION ALL SELECT 10 seq, 'AAPERR_PRICE_MATRIX_OVERRIDE_LIST_PRICE_FAILED ' NAME, 0 STOREENT_ID, -1 LANGUAGE_ID, 'Error while overriding List Price from Price Matrix.' VALUE, '' DESCRIPTION, current timestamp LASTUPDATE FROM SYSIBM.DUAL
    
)) AS T
ON (X.NAME = T.NAME AND X.LANGUAGE_ID = T.LANGUAGE_ID)
WHEN MATCHED THEN
  UPDATE SET
    VALUE = T.VALUE,
    LASTUPDATE = CURRENT TIMESTAMP
WHEN NOT MATCHED THEN
  INSERT (X_PROPERTY_ID, NAME, LANGUAGE_ID, STOREENT_ID, VALUE, LASTUPDATE)
  VALUES (T.X_PROPERTY_ID, T.NAME, T.LANGUAGE_ID, T.STOREENT_ID, T.VALUE, CURRENT TIMESTAMP);
  